server {
    listen 80 ; 
    listen 443 ssl http2 ; 
   
    ......忽略......

    location ^~ /.well-known/acme-challenge {
        allow all; 
        root /usr/share/nginx/html; 
    }
    # 找到↑这个位置  开始复制粘贴
    # 后台前端反向代理→编辑→把下面两段/api/ 和 /uploads 复制粘贴进来  9007是API服务端口号 更改为自己的
    location /api/ {
        proxy_pass http://127.0.0.1:9007/api/;
        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /uploads/ {
        proxy_pass http://127.0.0.1:9007/uploads/;
        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    # 到这里结束  下面的不用复制 不用管

    include /www/sites/admin.xxx.com/proxy/*.conf; 

    if ($scheme = http) {
        return 301 https://$host$request_uri; 
    }

   ......保持原有的...